/******************************************************************************
 *    Copyright (c) Open Connectivity Foundation (OCF), AllJoyn Open Source
 *    Project (AJOSP) Contributors and others.
 *    
 *    SPDX-License-Identifier: Apache-2.0
 *    
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *    
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *    
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *    WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *    WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *    DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *    PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *    TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *    PERFORMANCE OF THIS SOFTWARE.
*
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_PulseEffectV2 */

#ifndef _Included_org_allseen_lsf_PulseEffectV2
#define _Included_org_allseen_lsf_PulseEffectV2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setToLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setToLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getToLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectV2_getToLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setFromLampState
 * Signature: (Lorg/allseen/lsf/LampState;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setFromLampState
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getFromLampState
 * Signature: ()Lorg/allseen/lsf/LampState;
 */
JNIEXPORT jobject JNICALL Java_org_allseen_lsf_PulseEffectV2_getFromLampState
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setToPresetID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setToPresetID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getToPresetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PulseEffectV2_getToPresetID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setFromPresetID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setFromPresetID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getFromPresetID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_PulseEffectV2_getFromPresetID
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setPulsePeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setPulsePeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getPulsePeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffectV2_getPulsePeriod
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setPulseDuration
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setPulseDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getPulseDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffectV2_getPulseDuration
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    setNumPulses
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_setNumPulses
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    getNumPulses
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_allseen_lsf_PulseEffectV2_getNumPulses
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    createNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_createNativeObject
  (JNIEnv *, jobject);

/*
 * Class:     org_allseen_lsf_PulseEffectV2
 * Method:    destroyNativeObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_allseen_lsf_PulseEffectV2_destroyNativeObject
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif