/******************************************************************************
 *    Copyright (c) Open Connectivity Foundation (OCF), AllJoyn Open Source
 *    Project (AJOSP) Contributors and others.
 *    
 *    SPDX-License-Identifier: Apache-2.0
 *    
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *    
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *    
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *    WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *    WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *    DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *    PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *    TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *    PERFORMANCE OF THIS SOFTWARE.
*
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_LampManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_LampManagerCallbackTest
#define _Included_org_allseen_lsf_test_LampManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getAllLampIDsReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getAllLampIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    setLampNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_setLampNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampManufacturerReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampManufacturerReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampsFoundCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampsFoundCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampsLostCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampsLostCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampParametersEnergyUsageMilliwattsFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampParametersEnergyUsageMilliwattsFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampNameChangedCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampNameChangedCB
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampDetailsReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampDetails;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampDetailsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampParametersReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampParameters;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampParametersReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampParametersLumensFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampParametersLumensFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jboolean);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    pulseLampWithStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_pulseLampWithStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    pulseLampWithPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_pulseLampWithPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampServiceVersionReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampServiceVersionReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateToPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateToPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampSupportedLanguagesReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampSupportedLanguagesReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    setLampEffectReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_setLampEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampState;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    resetLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_resetLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    lampStateChangedCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Ljava/lang/String;Lorg/allseen/lsf/LampState;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_lampStateChangedCB
  (JNIEnv *, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    transitionLampStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_transitionLampStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    getLampFaultsReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_getLampFaultsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlongArray);

/*
 * Class:     org_allseen_lsf_test_LampManagerCallbackTest
 * Method:    clearLampFaultReplyCB
 * Signature: (Lorg/allseen/lsf/LampManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampManagerCallbackTest_clearLampFaultReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif