/******************************************************************************
 *    Copyright (c) Open Connectivity Foundation (OCF), AllJoyn Open Source
 *    Project (AJOSP) Contributors and others.
 *    
 *    SPDX-License-Identifier: Apache-2.0
 *    
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *    
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *    
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *    WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *    WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *    DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *    PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *    TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *    PERFORMANCE OF THIS SOFTWARE.
*
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_MasterSceneManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_MasterSceneManagerCallbackTest
#define _Included_org_allseen_lsf_test_MasterSceneManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    getAllMasterSceneIDsReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_getAllMasterSceneIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    getMasterSceneNameReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_getMasterSceneNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    setMasterSceneNameReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_setMasterSceneNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    masterScenesNameChangedCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_masterScenesNameChangedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    masterScenesCreatedCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_masterScenesCreatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    masterScenesDeletedCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_masterScenesDeletedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    masterScenesUpdatedCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_masterScenesUpdatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    masterScenesAppliedCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_masterScenesAppliedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    getMasterSceneReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/MasterScene;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_getMasterSceneReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    createMasterSceneReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_createMasterSceneReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    deleteMasterSceneReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_deleteMasterSceneReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    updateMasterSceneReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_updateMasterSceneReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    applyMasterSceneReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_applyMasterSceneReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_MasterSceneManagerCallbackTest
 * Method:    createMasterSceneWithTrackingReplyCB
 * Signature: (Lorg/allseen/lsf/MasterSceneManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_MasterSceneManagerCallbackTest_createMasterSceneWithTrackingReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif