/******************************************************************************
 *    Copyright (c) Open Connectivity Foundation (OCF), AllJoyn Open Source
 *    Project (AJOSP) Contributors and others.
 *    
 *    SPDX-License-Identifier: Apache-2.0
 *    
 *    All rights reserved. This program and the accompanying materials are
 *    made available under the terms of the Apache License, Version 2.0
 *    which accompanies this distribution, and is available at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *    
 *    Copyright (c) Open Connectivity Foundation and Contributors to AllSeen
 *    Alliance. All rights reserved.
 *    
 *    Permission to use, copy, modify, and/or distribute this software for
 *    any purpose with or without fee is hereby granted, provided that the
 *    above copyright notice and this permission notice appear in all
 *    copies.
 *    
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
 *    WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
 *    WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
 *    AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
 *    DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
 *    PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
 *    TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *    PERFORMANCE OF THIS SOFTWARE.
*
 ******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_allseen_lsf_test_LampGroupManagerCallbackTest */

#ifndef _Included_org_allseen_lsf_test_LampGroupManagerCallbackTest
#define _Included_org_allseen_lsf_test_LampGroupManagerCallbackTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    getAllLampGroupIDsReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_getAllLampGroupIDsReplyCB
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    getLampGroupNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_getLampGroupNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    setLampGroupNameReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_setLampGroupNameReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    getLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Lorg/allseen/lsf/LampGroup;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_getLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jobject);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsNameChangedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsNameChangedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsUpdatedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsUpdatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    createLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_createLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsCreatedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsCreatedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    deleteLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_deleteLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    lampGroupsDeletedCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_lampGroupsDeletedCB
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    pulseLampGroupWithStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_pulseLampGroupWithStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    pulseLampGroupWithPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_pulseLampGroupWithPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateOnOffFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateOnOffFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateHueFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateHueFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateSaturationFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateSaturationFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateBrightnessFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateBrightnessFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    resetLampGroupStateColorTempFieldReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_resetLampGroupStateColorTempFieldReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    updateLampGroupReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_updateLampGroupReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    transitionLampGroupStateToPresetReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_transitionLampGroupStateToPresetReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    createLampGroupWithTrackingReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_createLampGroupWithTrackingReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jlong);

/*
 * Class:     org_allseen_lsf_test_LampGroupManagerCallbackTest
 * Method:    setLampGroupEffectReplyCB
 * Signature: (Lorg/allseen/lsf/LampGroupManagerCallback;Lorg/allseen/lsf/ResponseCode;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_allseen_lsf_test_LampGroupManagerCallbackTest_setLampGroupEffectReplyCB
  (JNIEnv *, jobject, jobject, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif